FROM node:22-alpine

WORKDIR /app

# Set npm registry argument
ARG NPM_REGISTRY=https://registry.npmjs.org

# Set npm registry
RUN npm config set registry $NPM_REGISTRY

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port
EXPOSE 3040

# Start the application in development mode
CMD ["npm", "run", "dev"]
