version: '3.8'

services:
  # Auth service
  auth:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: neurallog-auth
    ports:
      - "3040:3040"
    environment:
      - NODE_ENV=production
      - PORT=3040
      - OPENFGA_HOST=openfga
      - OPENFGA_PORT=8080
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=neurallog_auth
    depends_on:
      - openfga
      - postgres
    restart: unless-stopped

  # OpenFGA service
  openfga:
    image: openfga/openfga:latest
    container_name: neurallog-openfga
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:postgres@postgres:5432/openfga
      - OPENFGA_AUTHN_METHOD=none
      - OPENFGA_LOG_LEVEL=info
      - OPENFGA_PLAYGROUND_ENABLED=true
    depends_on:
      - postgres
    restart: unless-stopped

  # PostgreSQL service
  postgres:
    image: postgres:14-alpine
    container_name: neurallog-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openfga
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
