apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neurallog-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
