apiVersion: v1
kind: Service
metadata:
  name: neurallog-postgres
  labels:
    app: neurallog-postgres
spec:
  selector:
    app: neurallog-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
